/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package module.jpa;

import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.assertTrue;

import java.util.List;

import module.jpa.dao.EventDao;
import module.jpa.modles.Event;

public class LibraryTest {
    @Test 
    public void testSomeLibraryMethod() {
        EventDao testEventDAO = new EventDao();
        Event expected = new Event("Concert", "Rochester", "8:00PM");

        //persist
        testEventDAO.createEvent(expected);
        List<Event> actual = testEventDAO.readAllEvents();

        assertTrue(actual.contains(expected));
    }
}
